#%RAML 1.0 Library

types:
  Account:
    properties:
      Id: string
      Name: string
      AccountNumber: string

  Contact:
    properties:
      Id: string
      FirstName: string
      LastName: string
      Email: string

  Opportunity:
    properties:
      Id: string
      Name: string
      StageName: string
      Amount: number

  CustomObject:
    properties:
      Id: string
      Name: string
      CustomField: string
